### PR TITLE
Handle lowercase etag header response in Multipart requests

### PR DESCRIPTION
**Pull request by dekelpilli**
This is a change to also handle a lowercase `etag` header in the response. This style of header is used by [GarageHQ](https://garagehq.deuxfleurs.fr/), which claims to be [fully compatible with S3 in the context of multipart requests](https://garagehq.deuxfleurs.fr/documentation/reference-manual/s3-compatibility/). I've also tested this with the official Java AWS client (V2) and it does handle the lowercase header without problems.

### CODE REVIEW

**Review by davidmoten — COMMENTED** [review]
Thanks for this. The http specification says that http header names are case insensitive so I've knocked up a [PR](https://github.com/davidmoten/aws-lightweight-client-java/pull/196) to make the `firstHeader` method case-insensitive to address this. Can you review that for me and confirm it will fix your problem?

**Comment by davidmoten** [comment]
Thanks for the review of the PR, I'll close this in favour of it.

**Comment by davidmoten** [comment]
[0.1.18](https://github.com/davidmoten/aws-lightweight-client-java/releases/tag/0.1.18) is on Maven Central now with the fix.

**Comment by dekelpilli** [comment]
Thanks, I can confirm that upgrading to 0.1.18 has fixed the issue for us

**Pull request closed without merging**
